language: python
os:
- linux
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install flake8
install:
- pip install .
stages:
- lint
- test
jobs:
  include:
  - stage: lint
    script: flake8 --max-line-length 120
script: pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: "qTrWk2T3w0kuIPrgQU406L7y+qJB/D1xSjSLEUjYi7OvJrMYDKitYuX+2ab+wkMuohERS1HG5JrbpyREHb21qalafBGCV+sMJ7JKXLoCSEWRJ97Se5F/55tpDs1PA4pdREiCJsjtDMVY87Kq9dPtms3oq/4kBLGvXESGN9c0XW5zEldBI+WhnM4DZYS/vWev7d7RbgE35YyJ6Y0Lf0UTfve4YQzLIKx6Mgx5nluw8J136//H3s93LNUOEodWD8VjrLOhLfNPjctWZ9lRV3Pend8tjTA6ht7CrGM+3ZaQXakfYbwXjM03VnYEbjfCGh0EMWGClzOOdoAjByxEOyRjbG1KCe0U/caw9dK2aDTNCYoT7GVe4gLtvhPtcXx8zR0tUsvWQiLYZLnsCfdnDiFoVlTGWNuBaqr1LcwghNZOKK6s1x8knB0nDx8nlAg79mhSUx0d6ukjavhOV6Dw19E9fXNaX3FZV/EyO++5Ayj0SQl5JDX9BYpFwNM39QbxWBQh8Tv6KTsumE9Zb5Y09++Z9LJRui+V/uVmsBySXHWbFdLP7o0Gxfyj60ERAgIk37jXkgyP9ez+EMTFpA2aat4j75q8FO/CKdJbbhEOZP2IyLng7FqbWy3kprIHpFNYnch6rOSSH/JRRgtXdiSSxK+t7Oh/1URucDQLVBeaDgBtQLo="
  on:
    tags: true
  skip_existing: true
