language: python
os:
- linux
python:
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install flake8
install:
- pip install .
stages:
- lint
- test
- deploy
script: pytest
jobs:
  include:
  - stage: lint
    script: flake8 --max-line-length 120
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      user: __token__
      password:
        secure: TWb2fdSC6zRUB4wXTa2pXZaTtzHUd69Ibati6JeNjFAcXzMIRd4iqF1cNiC4JESRogbb3xwma7kphYOdgt37EXlJkM008zuBAW9+h9K8kp4phueqWDnJcC7/Su6FI4B0fRgdNZH2JYlcUaxoewiKa3t4bVc3hUsOcrUKXLbX8PQTVdZZTPSPb0ZRCp+/lAkYGYlfwJa08+5lndl6zpGM/DyXewv5qto24uHN5Q+kwH1U+WoeG1br5yJXIyI3vtoR5tZxXKJ21qKShyJrQOCEyXPCrm996lIDptyIQznFSRny3MreK5Xu9u5JFHEEkSY9vHTU0+qjd1jeWGG9cnMH5oZK8bW/fa9S8HOh9JHSlNXNO6us/kTtqyVsJJcPynkeHXw4ARbsnh2QEe3a2EnR3FkKL8RpL8b9uBxY5QzF4BESbgA8RjOeaoTAUfCqN21vcBhWAP+uOCR7d1bR+cBQRgKvukKCt1lExup2MmE2XB9jBVl+ATV8FdZ2AMoE9losgNjWEGr5WHUXCfG9/ufG1ebfa9pvKL9bYQq2jaaq35le5LIh/MCfhv3C7n1vu4TGzDeqotqmJSNYmOATGX6mQU8vcpysxxv+613/SqNaz0PptjfEvKe+WNkdIf0Y8SOnifYZ+8BF28Lw/8Bk/P/I2oAcKs/ejNaFGApeu8lbxMo=
      on:
        tags: true
      skip_existing: true
